# Generated by Django 5.1.3 on 2025-03-18 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0001_initial"),  # Dependency on the initial migration
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="username",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),  # Add 'username' field to BlogPost model
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),  # Content of the comment
                ("created_at", models.DateTimeField(auto_now_add=True)),  # Timestamp when the comment was created
                (
                    "blogpost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blogpost.blogpost",  # Foreign key to the BlogPost model
                    ),
                ),
            ],
        ),
    ]
