# Generated by Django 5.1.3 on 2025-03-18 14:18

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0002_blogpost_username_comment"),  # Dependency on the previous migration
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="username",
            new_name="name",  # Rename the field 'username' to 'name'
        ),
    ]
